### ISSUE TITLE
About 3D semantic keypoints on the predicted mesh

### ISSUE THREAD

**Issue by lhiceu** [lkeab/gsnet#10]
Hi, I have a question about 3D semantic keypoints on the predicted mesh as you mentioned eq(2) above in your paper? How to get them? Are they generated along with model reconstruction?

**Comment by lkeab** [comment]
By mapping 2D semantic keypoints (provided by the annotation) back to the 3d mesh space using GT camera intrinsic, and finding the nearest 3d vertices.

**Comment by xxlbigbrother** [comment]
> 
hi! GSNet is a good work！Can you share 3d key-points of 79 car meshs?  and can you share that 2D semantic keypoints (provided by the annotation) don't have depth or z, how to map 2D keypoints back to the 3d mesh space?

**Comment by tingyihello** [comment]
> work！Can you share 3d key-points of 79 car meshs? and can you share that 2D semantic keypoints (provided by the annotation) don't have depth or z, how to map 2D keypoints back to the 3d mesh space?

+1
