### ISSUE TITLE
Geometric consistency loss

### ISSUE THREAD

**Issue by srikanthmalla** [lkeab/gsnet#12]
Hi @lkeab, First of all, thank you for such a nice work! and making it public. I am curious how you are doing the geoemtric consistency loss (because it looks like there are no 3D semantic coordinates as mentioned in the paper). Could you please point me where this is implemented in your code?

Thank you,
Srikanth

**Comment by lkeab** [comment]
Thanks for watching our work. We project 3D semantic point on car meshes to 2D image to form geometric consistent loss. The 3D kpts are obtained by mapping the defined 2D semantic keypoints (provided by the annotation) back to the 3d mesh space using GT camera intrinsic, and finding the nearest 3d vertices. 

The mapping relation is stored [here](https://github.com/lkeab/gsnet/blob/69c418fd5c8ec9ee90b4298888f59d9ce5b37749/reference_code/GSNet-release/detectron2/modeling/roi_heads/roi_heads.py#L543). The public code only provides the inference part but it is easy to implement the projection loss given both 2D&3D kpts and camera intrinsics using the projection matrix.
