### ISSUE TITLE
Abrut kill happening when trying to run the demo.py

### ISSUE THREAD

**Issue by rohithagaram** [lkeab/gsnet#13]
Hello,

Firstly, thanks for the codes of your impressive research.

when i tired to the below command to to execute the demo.py  ( **i don't see the datasets folder** )
CUDA_VISIBLE_DEVICES=0 python3 demo/demo.py --config-file configs/COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x_apollo.yaml \
  --input 'datasets/coco/val_apollo/' \
  --output 'medium_result_val/' \
  --opts MODEL.WEIGHTS ./output/model_final.pth 

by reading the parser arguments i learnt --input should be list of input images with this i changed the command as follows

**command** : CUDA_VISIBLE_DEVICES=0  python3 demo/demo.py --config-file configs/COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x_apollo.yaml --input 'datasets/apollo/annotations/test/images/171206_034559609_Camera_5.jpg' --output 'medium_result_val/' --opts MODEL.WEIGHTS ./output/model_final.pth

**Output** 
name: coco_2014_train
name: coco_2014_val
name: coco_2014_minival
name: coco_2014_minival_100
name: coco_2014_valminusminival
name: coco_2017_train
name: coco_2017_val
name: coco_2017_occ
name: coco_2017_test
name: coco_2017_test-dev
name: coco_2017_val_100
name: apollo_train
name: apollo_val
name: keypoints_coco_2014_train
name: keypoints_coco_2014_val
name: keypoints_coco_2014_minival
name: keypoints_coco_2014_valminusminival
name: keypoints_coco_2014_minival_100
name: keypoints_coco_2017_train
name: keypoints_coco_2017_val
name: keypoints_coco_2017_val_100
[10/13 00:22:46 detectron2]: Arguments: Namespace(config_file='configs/COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x_apollo.yaml', webcam=False, video_input=None, input=['datasets/apollo/annotations/test/images/171206_034559609_Camera_5.jpg'], output='medium_result_val/', confidence_threshold=0.5, opts=['MODEL.WEIGHTS', './output/model_final.pth'])

**Killed**

can you please help me where I'm going wrong

**Comment by lkeab** [comment]
Hi, could you report more detailed error message for program being killed? '--input ' should be a folder containing input images.

**Comment by rohithagaram** [comment]
Hi , thanks for the reply .
           tried to change the '--input' arg pointing to image directory but still the issue exist
complete output as follows :
(pytorch) ragaram@gnode39:~/gsnet/reference_code/GSNet-release$ CUDA_VISIBLE_DEVICES=0 python3 demo/demo.py --config-file configs/COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x_apollo.yaml   --input '/home2/ragaram/gsnet/reference_code/GSNet-release/input_images'   --output 'medium_result_val/'   --opts MODEL.WEIGHTS ./output/model_final.pth
name: coco_2014_train
name: coco_2014_val
name: coco_2014_minival
name: coco_2014_minival_100
name: coco_2014_valminusminival
name: coco_2017_train
name: coco_2017_val
name: coco_2017_occ
name: coco_2017_test
name: coco_2017_test-dev
name: coco_2017_val_100
name: apollo_train
name: apollo_val
name: keypoints_coco_2014_train
name: keypoints_coco_2014_val
name: keypoints_coco_2014_minival
name: keypoints_coco_2014_valminusminival
name: keypoints_coco_2014_minival_100
name: keypoints_coco_2017_train
name: keypoints_coco_2017_val
name: keypoints_coco_2017_val_100
[10/13 20:56:44 detectron2]: Arguments: Namespace(config_file='configs/COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x_apollo.yaml', webcam=False, video_input=None, input=['/home2/ragaram/gsnet/reference_code/GSNet-release/input_images'], output='medium_result_val/', confidence_threshold=0.5, opts=['MODEL.WEIGHTS', './output/model_final.pth'])
done cfg
Killed

**Comment by lkeab** [comment]
I think it may be the problem of wrong pytorch or cuda versions. Make sure detectron2, pytorch and cuda are matched and installed correctly. The reported error log does not contain enough information for me.
