### ISSUE TITLE
kpts_mapping

### ISSUE THREAD

**Issue by engineerkong** [lkeab/gsnet#17]
Hi, firstly thanks for your work.
I have a question about the relationship between 1352 vertices and 66 keypoints. There is a file, named kpts_mapping.npy. It's not really used in your code as I understand. What means the content of this file? And how could I understand the relationship between mesh vertices and detected keypoints?
Thanks a lot.

**Comment by lkeab** [comment]
Hi, it is used [here](https://github.com/lkeab/gsnet/blob/master/reference_code/GSNet-release/detectron2/modeling/roi_heads/roi_heads.py#L543).  Please refer to the discussion [here](https://github.com/lkeab/gsnet/issues/12) and [here](https://github.com/lkeab/gsnet/issues/10).

**Comment by engineerkong** [comment]
Hi lkeab,
Thank you for your answer. As I searched, this file has not been called in code, only been defined in roi_heads.py. So I am little confused. Because I want to know the relation but don't understand the meaning of the 66*10*2 matrix in this file. Maybe you can help me to understand it.
Thanks for your patience.

**Comment by lkeab** [comment]
please see the reply [here](https://github.com/lkeab/gsnet/issues/9#issuecomment-862542808) for why roi_head.py does not execute.

**Comment by engineerkong** [comment]
Hi,
maybe here is the question. Since we may not have training code, I don't really understand the content of kpts_mapping.json, which you said stored the mapping relation from training process. How to understand this relation and why the content is 66 * 10 * 2 instead of 66 * 1?
Thanks a lot

**Comment by engineerkong** [comment]
Sorry, I mean the file kpts_mapping.npy

**Comment by 0ohadeso0** [comment]
> Hi, maybe here is the question. Since we may not have training code, I don't really understand the content of kpts_mapping.json, which you said stored the mapping relation from training process. How to understand this relation and why the content is 66 * 10 * 2 instead of 66 * 1? Thanks a lot

Hi, have you figured out how to use the kpts_mapping.npy and why the content is 66 * 10 * 2 ?
