### ISSUE TITLE
AttributeError: Cannot find field 'predict_trans' in the given Instances!

### ISSUE THREAD

**Issue by ahmeddawy** [lkeab/gsnet#18]
I'm trying to run the run.sh script in order to give a try to the provided demo, but I got the following error 

 File "/usr/local/lib/python3.7/dist-packages/detectron2/structures/instances.py", line 65, in __getattr__
    raise AttributeError("Cannot find field '{}' in the given Instances!".format(name))
AttributeError: Cannot find field 'predict_trans' in the given Instances!

My environment :
torchvision=0.6.0
CUDA = cu10.1
torch=1.5.0

**Comment by lkeab** [comment]
please refer to the discussion [here](https://github.com/lkeab/gsnet/issues/9)
