### ISSUE TITLE
Training codes

### ISSUE THREAD

**Issue by Haotian-Zhang** [lkeab/gsnet#2]
Hi @lkeab ,

Thanks for the great work! I wonder if you will be able to share the training codes and some detailed training procedures so we are able to train the model ourselves. Please let us know if that's possible, thank you!

**Comment by lkeab** [comment]
Sorry for the late reply. The training network for our full model except the co-plane constraints can be easily obtained by adapting the provided inference code.  I will update the project page once it is allowed.
