### ISSUE TITLE
Missing attributes 

### ISSUE THREAD

**Issue by ofir-dl** [lkeab/gsnet#5]
I am trying to run bash.run, unsuccessfully.

I get  an attribute Error:
`AttributeError: Cannot find field 'predict_rotation' in the given Instances!`

There  are other fields missing as well... 
Any ideas?

Thanks!

**Comment by lkeab** [comment]
Thanks for watching our work.

Could you tell me which line produce this error?

The field "predict_rotation" is defined in [here](https://github.com/lkeab/gsnet/blob/master/reference_code/GSNet-release/detectron2/modeling/roi_heads/roi_heads.py#L753).

**Comment by ofir-dl** [comment]
Thank you for the fast response!

Actually the first time I get this error is at line 104 of predictor.py (run_on_image function):
`for index in range(instances.predict_trans.shape[0]):`

The error is:
`raise AttributeError("Cannot find field '{}' in the given Instances!".format(name))
AttributeError: Cannot find field 'predict_trans' in the given Instances!`

Later on, I get the exact same error for `predict_rotation` at line 114 of predictor.py. 

Maybe it has something to do with this warning I get when running run.sh and using the pretrained model "model_final.pth"?
`Some model parameters or buffers are not found in the checkpoint:
roi_heads.box_predictor.bbox_pred.{bias, weight}
roi_heads.keypoint_head.score_lowres.{bias, weight}
`

**Comment by lkeab** [comment]
That's strange. When you run bash run.sh, has this pL752-754](https://github.com/lkeab/gsnet/blob/master/reference_code/GSNet-release/detectron2/modeling/roi_heads/roi_heads.py#L753) been executed?

**Comment by ofir-dl** [comment]
I did some debugging and figured out lines 752- 754 are not executed... :/
When I run bash.sh this is what I get:

`bash run.sh
running build
running build_py
running build_ext
running develop
running egg_info
writing detectron2.egg-info/PKG-INFO
writing dependency_links to detectron2.egg-info/dependency_links.txt
writing requirements to detectron2.egg-info/requires.txt
writing top-level names to detectron2.egg-info/top_level.txt
reading manifest file 'detectron2.egg-info/SOURCES.txt'
writing manifest file 'detectron2.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-3.8/detectron2/_C.cpython-38-x86_64-linux-gnu.so -> detectron2
Creating /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages/detectron2.egg-link (link to .)
detectron2 0.1 is already the active version in easy-install.pth

Installed /disk1/ofirbrenner/gsnet/reference_code/GSNet-release
Processing dependencies for detectron2==0.1
Searching for pydot==1.4.2
Best match: pydot 1.4.2
Adding pydot 1.4.2 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for future==0.18.2
Best match: future 0.18.2
Adding future 0.18.2 to easy-install.pth file
Installing futurize script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin
Installing pasteurize script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for fvcore==0.1.5.post20210514
Best match: fvcore 0.1.5.post20210514
Adding fvcore 0.1.5.post20210514 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for tensorboard==2.5.0
Best match: tensorboard 2.5.0
Adding tensorboard 2.5.0 to easy-install.pth file
Installing tensorboard script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for tqdm==4.60.0
Best match: tqdm 4.60.0
Adding tqdm 4.60.0 to easy-install.pth file
Installing tqdm script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for matplotlib==3.4.2
Best match: matplotlib 3.4.2
Adding matplotlib 3.4.2 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for cloudpickle==1.6.0
Best match: cloudpickle 1.6.0
Adding cloudpickle 1.6.0 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for tabulate==0.8.9
Best match: tabulate 0.8.9
Adding tabulate 0.8.9 to easy-install.pth file
Installing tabulate script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for yacs==0.1.8
Best match: yacs 0.1.8
Adding yacs 0.1.8 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for Pillow==8.1.1
Best match: Pillow 8.1.1
Processing Pillow-8.1.1-py3.8-linux-x86_64.egg
Pillow 8.1.1 is already the active version in easy-install.pth

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages/Pillow-8.1.1-py3.8-linux-x86_64.egg
Searching for termcolor==1.1.0
Best match: termcolor 1.1.0
Adding termcolor 1.1.0 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for pyparsing==2.4.7
Best match: pyparsing 2.4.7
Adding pyparsing 2.4.7 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for numpy==1.20.1
Best match: numpy 1.20.1
Adding numpy 1.20.1 to easy-install.pth file
Installing f2py script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin
Installing f2py3 script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin
Installing f2py3.8 script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for iopath==0.1.8
Best match: iopath 0.1.8
Adding iopath 0.1.8 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for PyYAML==5.4.1
Best match: PyYAML 5.4.1
Adding PyYAML 5.4.1 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for absl-py==0.12.0
Best match: absl-py 0.12.0
Adding absl-py 0.12.0 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for protobuf==3.17.0
Best match: protobuf 3.17.0
Adding protobuf 3.17.0 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for setuptools==52.0.0.post20210125
Best match: setuptools 52.0.0.post20210125
Adding setuptools 52.0.0.post20210125 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for Werkzeug==2.0.0
Best match: Werkzeug 2.0.0
Adding Werkzeug 2.0.0 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for grpcio==1.37.1
Best match: grpcio 1.37.1
Adding grpcio 1.37.1 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for google-auth-oauthlib==0.4.4
Best match: google-auth-oauthlib 0.4.4
Adding google-auth-oauthlib 0.4.4 to easy-install.pth file
Installing google-oauthlib-tool script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for google-auth==1.30.0
Best match: google-auth 1.30.0
Adding google-auth 1.30.0 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for tensorboard-data-server==0.6.1
Best match: tensorboard-data-server 0.6.1
Adding tensorboard-data-server 0.6.1 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for requests==2.25.1
Best match: requests 2.25.1
Adding requests 2.25.1 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for wheel==0.36.2
Best match: wheel 0.36.2
Processing wheel-0.36.2-py3.8.egg
wheel 0.36.2 is already the active version in easy-install.pth
Installing wheel script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages/wheel-0.36.2-py3.8.egg
Searching for tensorboard-plugin-wit==1.8.0
Best match: tensorboard-plugin-wit 1.8.0
Adding tensorboard-plugin-wit 1.8.0 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for Markdown==3.3.4
Best match: Markdown 3.3.4
Adding Markdown 3.3.4 to easy-install.pth file
Installing markdown_py script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for cycler==0.10.0
Best match: cycler 0.10.0
Adding cycler 0.10.0 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for python-dateutil==2.8.1
Best match: python-dateutil 2.8.1
Adding python-dateutil 2.8.1 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for kiwisolver==1.3.1
Best match: kiwisolver 1.3.1
Adding kiwisolver 1.3.1 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for portalocker==2.3.0
Best match: portalocker 2.3.0
Adding portalocker 2.3.0 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for six==1.15.0
Best match: six 1.15.0
Adding six 1.15.0 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for requests-oauthlib==1.3.0
Best match: requests-oauthlib 1.3.0
Adding requests-oauthlib 1.3.0 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for pyasn1-modules==0.2.8
Best match: pyasn1-modules 0.2.8
Adding pyasn1-modules 0.2.8 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for cachetools==4.2.2
Best match: cachetools 4.2.2
Adding cachetools 4.2.2 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for rsa==4.7.2
Best match: rsa 4.7.2
Adding rsa 4.7.2 to easy-install.pth file
Installing pyrsa-decrypt script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin
Installing pyrsa-encrypt script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin
Installing pyrsa-keygen script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin
Installing pyrsa-priv2pub script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin
Installing pyrsa-sign script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin
Installing pyrsa-verify script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for certifi==2020.12.5
Best match: certifi 2020.12.5
Adding certifi 2020.12.5 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for chardet==4.0.0
Best match: chardet 4.0.0
Adding chardet 4.0.0 to easy-install.pth file
Installing chardetect script to /disk1/ofirbrenner/anaconda3/envs/gsnet/bin

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for idna==2.10
Best match: idna 2.10
Adding idna 2.10 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for urllib3==1.26.4
Best match: urllib3 1.26.4
Adding urllib3 1.26.4 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for oauthlib==3.1.0
Best match: oauthlib 3.1.0
Adding oauthlib 3.1.0 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Searching for pyasn1==0.4.8
Best match: pyasn1 0.4.8
Adding pyasn1 0.4.8 to easy-install.pth file

Using /disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages
Finished processing dependencies for detectron2==0.1
[05/16 12:37:07 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x_apollo.yaml', input=['images'], opts=['MODEL.WEIGHTS', './output/model_final.pth'], output='medium_result_val/', video_input=None, webcam=False)
Skip loading parameter 'roi_heads.box_predictor.bbox_pred.weight' to the model due to incompatible shapes: (4, 1024) in the checkpoint but (316, 1024) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.box_predictor.bbox_pred.bias' to the model due to incompatible shapes: (4,) in the checkpoint but (316,) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.keypoint_head.score_lowres.weight' to the model due to incompatible shapes: (512, 66, 4, 4) in the checkpoint but (512, 17, 4, 4) in the model! You might want to double check if this is expected.
Skip loading parameter 'roi_heads.keypoint_head.score_lowres.bias' to the model due to incompatible shapes: (66,) in the checkpoint but (17,) in the model! You might want to double check if this is expected.
Some model parameters or buffers are not found in the checkpoint:
roi_heads.box_predictor.bbox_pred.{bias, weight}
roi_heads.keypoint_head.score_lowres.{bias, weight}
The checkpoint state_dict contains keys that are not used by the model:
  roi_heads.fuse_roi_feature_conv.{bias, weight}
  roi_heads.fuse_roi_feature_conv_1.{bias, weight}
  roi_heads.fuse_roi_feature_conv_2.{bias, weight}
  roi_heads.fuse_heatmap_conv.{bias, weight}
  roi_heads.fuse_heatmap_conv_1.{bias, weight}
  roi_heads.fuse_heatmap_conv_2.{bias, weight}
  roi_heads.fuse_heatmap_conv_3.{bias, weight}
  roi_heads.fuse_box_pos.{bias, weight}
  roi_heads.fuse_box_pos_1.{bias, weight}
  roi_heads.fuse_kpts_pos.{bias, weight}
  roi_heads.fuse_kpts_pos_1.{bias, weight}
  roi_heads.regress_translation.{bias, weight}
  roi_heads.regress_rotation.{bias, weight}
  roi_heads.regress_car_params_0.{bias, weight}
  roi_heads.regress_car_params_1.{bias, weight}
  roi_heads.regress_car_params_2.{bias, weight}
  roi_heads.regress_car_params_3.{bias, weight}
  roi_heads.regress_car_cluster_type.{bias, weight}
  roi_heads.regress_car_cls.{bias, weight}
['images']
  0%|                                                                       | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo/demo.py", line 91, in <module>
    predictions, visualized_output = demo.run_on_image(img, save_name)
  File "/disk1/ofirbrenner/gsnet/reference_code/GSNet-release/demo/predictor.py", line 108, in run_on_image
    for index in range(instances.predict_trans.shape[0]):
  File "/disk1/ofirbrenner/anaconda3/envs/gsnet/lib/python3.8/site-packages/detectron2/structures/instances.py", line 65, in __getattr__
    raise AttributeError("Cannot find field '{}' in the given Instances!".format(name))
AttributeError: Cannot find field 'predict_trans' in the given Instances!
run.sh: line 6: 36568 Segmentation fault      (core dumped) CUDA_VISIBLE_DEVICES=0 python3 demo/demo.py --config-file configs/COCO-Keypoints/keypoint_rcnn_R_101_FPN_3x_apollo.yaml --input 'images' --output 'medium_result_val/' --opts MODEL.WEIGHTS ./output/model_final.pth`

**Comment by lkeab** [comment]
The mentioned code lines must be executed to guarantee the correct results. I think it is related to install environment. Have you install detectron2 following this [document](https://github.com/facebookresearch/detectron2/blob/master/INSTALL.md) correctly?

**Comment by ofir-dl** [comment]
I'll try reinstalling the environment.

Thanks!

**Comment by yuhanyuhang** [comment]
I meet the same question. have your solve it?

**Comment by yuhanyuhang** [comment]
I meet the same problem. Have you solved it?AttributeError: Cannot find field 'predict_trans' in the given Instances!

**Comment by lhiceu** [comment]
Same problem. 
Because of the config file

'''
    ROI_HEADS:
    NAME: "StandardROIHeads"
'''

the ROIHeads given in this project is not executed
